#!/usr/bin/env php
<?php
/*
    Modifications:
    zxv (http://github.com/zxv/)

    Original Author:
    David Phillips <david@acz.org>
*/

    require("lib/phpa.php");
    define("__PHPA_PROMPT", ">>> ");

    __phpa__setup();
    __phpa__print_info();

    if (count($argv) > 1) {
        require($argv[1]);
    }

    // The expected  name of the command-line script
    $phpa_command = "phpa";

    // The actual name of the command-line script
    $script_name = $_SERVER['SCRIPT_FILENAME'];
    $endOfScript = substr($script_name, -strlen($phpa_command));

    // If the name of the running script ends in the expected name
    if ($endOfScript == $phpa_command) {
        // Invoke the interactive prompt
        __phpa__interactive();
    }

?>
